# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint

#   update_frequency: 5.0
#   publish_frequency: 5.0
#   transform_tolerance: 0.5

#   static_map: true
#   rolling_window: true
#   track_unknown_space: true

# plugins:
#   - {name: obstacle_layer,  type: "costmap_2d::VoxelLayer"}
#   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true